export const RequestType = {
    REQUEST_GET_ADDRESS: 'REQUEST_GET_ADDRESS',
    REQUEST_GET_COIN_DETAILS: 'REQUEST_GET_COIN_DETAILS',
    REQUEST_GET_TRANSACTIONS: 'REQUEST_GET_TRANSACTIONS',
    REQUEST_GET_COIN_LIST: 'REQUEST_GET_COIN_LIST',
    REQUEST_GET_SEED: 'REQUEST_GET_SEED',
    REQUEST_SET_SEED: 'REQUEST_SET_SEED',
    REQUEST_INITIALIZE: 'REQUEST_INITIALIZE',
    REQUEST_LOG: 'REQUEST_LOG',
    REQUEST_ERROR: 'REQUEST_ERROR',
    REQUEST_WARN:'REQUEST_WARN'
}

export const ResponseType = {
    RESPONSE_GET_ADDRESS: 'RESPONSE_GET_ADDRESS',
    RESPONSE_GET_COIN_DETAILS: 'RESPONSE_GET_COIN_DETAILS',
    RESPONSE_GET_TRANSACTIONS: 'RESPONSE_GET_TRANSACTIONS',
    RESPONSE_GET_COIN_LIST: 'RESPONSE_GET_COIN_LIST',
    RESPONSE_GET_SEED: 'RESPONSE_GET_SEED',
    RESPONSE_SET_SEED: 'RESPONSE_SET_SEED',
    RESPONSE_INITIALIZE: 'RESPONSE_INITIALIZE',
    RESPONSE_ERROR: 'RESPONSE_ERROR',
}
